### ISSUE TITLE
Load local audio files

### ISSUE THREAD

**Issue by phmarek** [woheller69/audio-analyzer-for-android#23] opened 2024-04-08 14:13 UTC
It would be great if local files (eg., saved `WAV`s, media files, etc.) could be loaded for visualization.

Even better if "Share with" of audio files offers this App as destination!

**Comment by woheller69** [comment] 2024-04-08 15:07
Duplicate of #21 

I am not adding new features to the app. I am only updating it for new Android versions if needed.

**Closed by woheller69** 2024-04-08 15:07 UTC
